export const elementos = {
    logingText: ':nth-child(2) > .oxd-input-group > :nth-child(2) > .oxd-input',
    passwordText: ':nth-child(3) > .oxd-input-group > :nth-child(2) > .oxd-input',
    loginButton: '.oxd-button',
    menuAdmin: ':nth-child(1) > .oxd-main-menu-item > .oxd-text',
    botaoNovoUser: '.orangehrm-header-container > .oxd-button',
    comboUserRole: ':nth-child(1) > .oxd-input-group > :nth-child(2) > .oxd-select-wrapper > .oxd-select-text > .oxd-select-text-input',
    comboUserOptionsAdmin: '.oxd-select-dropdown > :nth-child(2)',
    comboUserOptionsESS: '.oxd-select-dropdown > :nth-child(3)',
    comboEmployeeName: '.oxd-autocomplete-text-input > input',
    comboEmployeeOptions: '.oxd-autocomplete-option',
    comboStatus: ':nth-child(3) > .oxd-input-group > :nth-child(2) > .oxd-select-wrapper > .oxd-select-text > .oxd-select-text-input',
    comboStatusOptionsEnabled: '.oxd-select-dropdown > :nth-child(2)',
    comboStatusOptionsDisabled: '.oxd-select-dropdown > :nth-child(3)',
    campoUserName: ':nth-child(4) > .oxd-input-group > :nth-child(2) > .oxd-input',
    campoPassword: '.user-password-cell > .oxd-input-group > :nth-child(2) > .oxd-input',
    campoConfirmarPassword: ':nth-child(2) > .oxd-input-group > :nth-child(2) > .oxd-input',
    botaoSalvar: '.oxd-button--secondary',
    campoBuscarUserName: ':nth-child(2) > .oxd-input',
    botaoPesquisar: '.oxd-form-actions > .oxd-button--secondary',
    alerta: '.oxd-toast',
    alertaDelete: '.oxd-text--toast-message',
    textoStatus: '.oxd-table-card > .oxd-table-row > :nth-child(5)',
    textoUsername: '.oxd-table-card > .oxd-table-row > :nth-child(2) > div',
    botaoEditar: '.oxd-table-cell-actions > :nth-child(2) > .oxd-icon',
    botaoExcluir: '.oxd-table-cell-actions > :nth-child(1) > .oxd-icon',
    mensagemDelete: '.orangehrm-text-center-align > .oxd-text',
    botaoConfirmarExclusao: '.oxd-button--label-danger',
    validacaoUsername: ':nth-child(4) > .oxd-input-group > .oxd-text',
    validacaoPassword: ':nth-child(1) > .oxd-input-group > .oxd-text',
    validacaoConfirmacaoPassword: ':nth-child(2) > .oxd-input-group > .oxd-text'
};
