export const elements = {
    logingText: ':nth-child(2) > .oxd-input-group > :nth-child(2) > .oxd-input',
    passwordText: ':nth-child(3) > .oxd-input-group > :nth-child(2) > .oxd-input',
    loginButton: '.oxd-button',
    menuAdmin: ':nth-child(1) > .oxd-main-menu-item > .oxd-text',
    buttonNewUser: '.orangehrm-header-container > .oxd-button',
    buttonCancel: '.oxd-button--ghost',
    dropDownUserRoleHome: ':nth-child(2) > .oxd-input-group > :nth-child(2) > .oxd-select-wrapper > .oxd-select-text',
    dropdownUserRole: ':nth-child(1) > .oxd-input-group > :nth-child(2) > .oxd-select-wrapper > .oxd-select-text > .oxd-select-text-input',
    dropdownUserOptionsAdmin: '.oxd-select-dropdown > :nth-child(2)',
    dropdownUserOptionsESS: '.oxd-select-dropdown > :nth-child(3)',
    dropdownEmployeeName: '.oxd-autocomplete-text-input > input',
    dropdownEmployeeOptions: '.oxd-autocomplete-option',
    dropdownStatus: ':nth-child(3) > .oxd-input-group > :nth-child(2) > .oxd-select-wrapper > .oxd-select-text > .oxd-select-text-input',
    dropdownStatusOptionsEnabled: '.oxd-select-dropdown > :nth-child(2)',
    dropdownStatusOptionsDisabled: '.oxd-select-dropdown > :nth-child(3)',
    fieldUserName: ':nth-child(4) > .oxd-input-group > :nth-child(2) > .oxd-input',
    fieldPassword: '.user-password-cell > .oxd-input-group > :nth-child(2) > .oxd-input',
    fieldConfirmPassword: ':nth-child(2) > .oxd-input-group > :nth-child(2) > .oxd-input',
    buttonSave: '.oxd-button--secondary',
    fieldSearchUserName: ':nth-child(2) > .oxd-input',
    buttonSearch: '.oxd-form-actions > .oxd-button--secondary',
    alert: '.oxd-toast',
    alertDelete: '.oxd-text--toast-message',
    textStatus: '.oxd-table-card > .oxd-table-row > :nth-child(5)',
    textUsername: '.oxd-table-card > .oxd-table-row > :nth-child(2) > div',
    buttonEdit: '.oxd-table-cell-actions > :nth-child(2) > .oxd-icon',
    buttonDelete: '.oxd-table-cell-actions > :nth-child(1) > .oxd-icon',
    mensageDelete: '.orangehrm-text-center-align > .oxd-text',
    buttonConfirmDelete: '.oxd-button--label-danger',
    validationUsername: ':nth-child(4) > .oxd-input-group > .oxd-text',
    validationPassword: ':nth-child(1) > .oxd-input-group > .oxd-text',
    validationConfirmPassword: ':nth-child(2) > .oxd-input-group > .oxd-text',
    alertLogin: '.oxd-alert-content > .oxd-text',
    textRequired: '.oxd-input-group > .oxd-text',
    menuLogout: '.oxd-userdropdown-tab > .oxd-icon',
    buttonLogout: ':nth-child(4) > .oxd-userdropdown-link'
};
